### ISSUE TITLE
Add unpacking functionality

### ISSUE THREAD

**Issue by RadValentin** [CookiePLMonster/GXT-Builder#1]
@CookiePLMonster Is it possible to make this tool unpack `.gxt` files to regular text files? I'm asking because I think this would be useful for two usecases:

1. You could version control the source text files through git this way.
2. When trying to add a translation for a new language, it'd be easier to be able to work directly with the unpacked source files. Personally I'd much rather use my own text editor versus something like [GXT Editor](http://www.gtagarage.com/mods/show.php?id=1074).

**Comment by CookiePLMonster** [comment]
Do you really need to unpack files for that though? You're supposed to maintain those in TXT format for translations - in fact, the entire "Advanced Usage" section concerns features I created just to support seamless and supervised creation of translations.

**Comment by RadValentin** [comment]
It's possible that I'm missing some key information, let me explain my use case. I have a mod that I worked on a good while back (~7 years) and from what I remember I kept the original translations (for menus, game tips, etc.) and just added new strings for my custom missions.

I want to translate that mod to another language but I'd like to keep the translations that Rockstar made for UI and stuff and just add in my custom mission text.

How would you suggest I proceed?

**Comment by CookiePLMonster** [comment]
Is this SA? If so, then you technically cannot unpack GXT back to text files because GXT entry names are not stored as is, but hashed.

I would recommend using any third party GXT editor to export your file (I'm 99% sure such editors exist) and then fishing out GXT entry names from whatever sources you have. You could also rely on Sanny Builder's documentations since it has GXTs of all 5 GTAs exported into a text file.

**Comment by CookiePLMonster** [comment]
Maybe this fork is going to have required functionality:

https://github.com/kagikn/GXT-Text-Replacer

As for GXT Builder itself, since it's a **builder** I don't plan on adding anything to allow unpacking GXTs. If anything, it'd be a tool separate to this (else I might as well rename it to gxtutils or so).

**Comment by RadValentin** [comment]
@CookiePLMonster Thanks for replying. I'll make sure to check out GXT-Text-Replacer for any future projects.
